server:
  port: 8761

eureka:
  instance:
    hostname: lichao
#    prefer-ip-address: true
#    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  server:
    # 关闭自我保护模式
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 30000 # 单位毫秒
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      # 当前服务注册到另一个server上，两个服务互相注册
      defaultZone: http://rilweic:8762/eureka/